name: Build TWRP Recovery Ramdisk Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Config Dependences
      run: |
        sudo apt install python3 python-is-python3 build-essential ccache g++-multilib gcc-multilib git libncurses5 curl

    - name: Repo Sync
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ./repo
        chmod +x ./repo
        export PATH=$PATH:$(pwd)/
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        cp ./.repo/repo/repo ./repo
        repo sync

    - name: Create Device Tree
      run: |
        mkdir -p device/honor/cornell
        git clone https://github.com/HoleHolo/android_device_honor_cornell.git ./device/honor/cornell --depth=1

    - name: Start to Build
      run: |
        export ALLOW_MISSING_DEPENDENCIES=true
        . build/envsetup.sh
        lunch twrp_cornell-eng
        mka recoveryimage

    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: recovery.img
        path: "recovery.img"
